services:
  - type: web
    name: animezone-backend
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
